Repository Sina-Soltani/Parbad, pull requests merged in 2021-08, with the labels that each got.

#237 Add FanAva Gateway
  Parbad.Gateway.FanAva.Test/FanAvaCommonTests.cs
  Parbad.Gateway.FanAva.Test/Parbad.Gateway.FanAva.Test.csproj
  Parbad.sln
  src/Parbad.Gateway/FanAva/src/FanAvaGateway.cs
  src/Parbad.Gateway/FanAva/src/FanAvaGatewayAccount.cs
  src/Parbad.Gateway/FanAva/src/FanAvaGatewayBuilderExtensions.cs
  src/Parbad.Gateway/FanAva/src/FanAvaGatewayInvoiceBuilderExtensions.cs
  src/Parbad.Gateway/FanAva/src/FanAvaGatewayOptions.cs
  src/Parbad.Gateway/FanAva/src/Internal/FanAvaHelper.cs
  src/Parbad.Gateway/FanAva/src/Internal/Models/FanAvaCallbackResultModel.cs
  src/Parbad.Gateway/FanAva/src/Internal/Models/FanAvaCheckRequestModel.cs
  src/Parbad.Gateway/FanAva/src/Internal/Models/FanAvaCheckResultModel.cs
  src/Parbad.Gateway/FanAva/src/Internal/Models/FanAvaRefundRequestModel.cs
  src/Parbad.Gateway/FanAva/src/Internal/Models/FanAvaRefundResultModel.cs
  src/Parbad.Gateway/FanAva/src/Internal/Models/FanAvaRequestModel.cs
  src/Parbad.Gateway/FanAva/src/Internal/Models/FanAvaRequestResultModel.cs
  src/Parbad.Gateway/FanAva/src/Internal/Models/FanAvaVerifyRequestModel.cs
  src/Parbad.Gateway/FanAva/src/Internal/Models/FanAvaVerifyResultModel.cs
  src/Parbad.Gateway/FanAva/src/Parbad.Gateway.FanAva.csproj
  src/Parbad.Gateway/FanAva/src/Parbad.Gateway.FanAva.xml
  src/Parbad.Gateway/FanAva/src/icon.png
  src/Parbad.Gateway/FanAva/src/readme.txt
Labels: feature

#242 fixing the issue with transporting in Linux servers.
  src/Parbad/src/Internal/DefaultGatewayTransporter.cs
Labels: bug

#243 Editable Gateway Transporter.
  src/Parbad/src/GatewayTransporterDescriptor.cs
  src/Parbad/src/Parbad.xml
Labels: Improvement

#244 Adding Payer ID to Mellat Gateway.
  src/Parbad/src/Gateway/Mellat/Internal/MellatHelper.cs
  src/Parbad/src/Gateway/Mellat/MellatGatewayAdditionalDataRequest.cs
  src/Parbad/src/Gateway/Mellat/MellatGatewayInvoiceBuilderExtensions.cs
  src/Parbad/src/Parbad.csproj
  src/Parbad/src/Parbad.xml
  src/Parbad/tests/Gateway/Mellat/MellatCommonTests.cs
Labels: Improvement

#245 fixing the mellat gateway additional data bug.
  src/Parbad/src/Gateway/Mellat/Internal/MellatHelper.cs
Labels: bug

#246 Update package details.
  src/Parbad/src/Parbad.csproj
Labels: feature
