Repository Sina-Soltani/Parbad, pull requests merged in 2025-03, with the labels that each got.

#410 Feature/cleanup pasargad gateway
  src/Parbad/src/Gateway/Pasargad/Api/IPasargadApi.cs
  src/Parbad/src/Gateway/Pasargad/Api/Models/PasargadGetTokenRequestModel.cs
  src/Parbad/src/Gateway/Pasargad/Api/Models/PasargadPurchaseRequestModel.cs
  src/Parbad/src/Gateway/Pasargad/Internal/Models/PasargadCallbackResultModel.cs
  src/Parbad/src/Gateway/Pasargad/Internal/PasargadApi.cs
  src/Parbad/src/Gateway/Pasargad/Internal/PasargadHelper.cs
  src/Parbad/src/Gateway/Pasargad/PasargadGateway.cs
  src/Parbad/src/Gateway/Pasargad/PasargadGatewayAccount.cs
  src/Parbad/src/Gateway/Pasargad/PasargadGatewayOptions.cs
  src/Parbad/src/Gateway/Pasargad/PasargadRequestAdditionalData.cs
  src/Parbad/src/Internal/PaymentRefundResult.cs
  src/Parbad/src/Internal/PaymentVerifyResult.cs
  src/Parbad/src/Parbad.xml
Labels: Improvement

#411 add nonce to gateway transporter because it violates the following Co…
  src/Parbad/src/Internal/DefaultGatewayTransporter.cs
  src/Parbad/src/Internal/HtmlFormBuilder.cs
  src/Parbad/src/Options/ParbadOptions.cs
Labels: bug, Improvement

#412 added nonce to virtual gateway
  src/Parbad/src/Gateway/ParbadVirtual/MiddlewareInvoker/ParbadVirtualGatewayMiddlewareInvoker.cs
  src/Parbad/src/Gateway/ParbadVirtual/VirtualGatewayRequestTemplate.html
  src/Parbad/src/Gateway/ParbadVirtual/VirtualGatewayResultTemplate.html
  src/Parbad/src/Internal/HtmlFormBuilder.cs
  src/Parbad/src/Options/ParbadOptions.cs
  src/Parbad/src/Parbad.csproj
  src/Parbad/src/Parbad.xml
Labels: feature, Improvement
